### ISSUE TITLE
UTIKit crashing Xcode when converting to Swift 4

### ISSUE THREAD

**Issue by EdsonGuido** [cockscomb/UTIKit#11]
When i try converting UTIKit to Swift 4 using the Xcode 9 converter, Xcode always crash, is anyone having the same issue?

**Comment by acalism** [comment]
Just use Xcode 9.2 instead, and it works for me.

**Comment by cockscomb** [comment]
The problem seems to be fixed in Xcode 9.2

> #### Swift Migration
> ##### Resolved Issues
> Opening the Swift Migration Assistant when a workspace or project contains a Swift Playground no longer crashes. (35175054)

https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html#//apple_ref/doc/uid/TP40001051-CH1-SW936
