### ISSUE TITLE
Update Podspecs for the "redundant public"

### ISSUE THREAD

**Issue by iNono22** [cockscomb/UTIKit#16]
Hi @cockscomb,
Can you update your Podspecs to include changes of https://github.com/cockscomb/UTIKit/commit/3f39c309e8fa30de9fed819b27e8766eee21cbb2 when update pod ?
Thanks

**Comment by cockscomb** [comment]
@arnaudWasappli Hi.
I just released the latest version of UTIKit.
https://cocoapods.org/pods/UTIKit
Sorry for the late release.

**Comment by iNono22** [comment]
Thanks ;-)
