### ISSUE TITLE
Swift 3.1 warning: Conditional downcast from 'CFString?'

### ISSUE THREAD

**Issue by jamesbebbington** [cockscomb/UTIKit#9]
Hey @cockscomb, thanks for sharing this useful little library.

I'm getting the following warning since upgrading our project to Swift 3.1:

`…/UTIKit/UTIKit/UTI.swift:241:82: Conditional downcast from 'CFString?' to 'String' is a bridging conversion; did you mean to use 'as'?`

**Comment by cockscomb** [comment]
Fixed in 2.0.1.

Thank you for your report @jamesbebbington 😄

**Comment by jamesbebbington** [comment]
Brilliant, that was quick. Thanks @cockscomb!
